### ISSUE TITLE
Unnecessary loop?

### ISSUE THREAD

**Issue by smu160** [bones-ai/rust-ants-colony-simulation#4]
https://github.com/bones-ai/rust-ants-colony-simulation/blob/3ecceb2bfa187ef1c36187e3f302ba9ffbd68c05/src/ant.rs#L125

This break statement makes the loop never execute. Is the loop needed?

**Comment by bones-ai** [comment]
Yes, using a loop isn't probably the best way to do it.

There's one line above `break`,
```
follow_pos.0 = transform.translation.truncate();
```
All it does is pick the first ant from the query and record its position for the camera to follow.
